on:
  pull_request:
    paths:
      - "server/**"
      - ".github/**"
jobs:
  build_and_test:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./server
      #      - run: cp .env.dev .env.local
      #        working-directory: ./web
      - run: npm test
        working-directory: ./server
