on:
  push:
    paths:
      - "server/**"
      - ".github/**"
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
        working-directory: ./server
      - uses: ./.github/actions/firebase
        with:
          args: deploy --debug --force --project lgtm-info-dev --only functions
        env:
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN }}"
