on:
  push:
    paths:
      - "web/**"
      - ".github/**"
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./web
      - run: cp .env.dev .env.local
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
      - name: Deploy Staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_DEV_PROJECT_ID }}'
