on:
  release:
    types: [published]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./web
      - run: cp .env.prod .env.local
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
        env:
          GENERATE_SOURCEMAP: "false"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_PROD_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "${{ secrets.FIREBASE_PROD_PROJECT_ID }}"
